language: node_js

node_js:
  - "stable"

cache:
  directories:
    - "node_modules"
  
script: 
  - npm run dev-tables-init
  - npm test
  - npm run coveralls

deploy:
  provider: heroku
  api_key: 
    secure: $HEROKU_API_KEY
  on: develop
  app: sans-stitches

services:
- postgresql

before_script:
  - psql -c 'create database sans_stitches;' -U postgres